% rebase("base.tpl", title="Page Title")
<p>This is generated by also rebasing modular2.tpl into the base.tpl. The advantage is that it very much looks like
    the page at modular1</p>
<p>This Page's content also has some variable content passed to the template() function in the
    .py file. This is variable --> {{variable}}</p>
