% rebase("base.tpl", title="Page Title")
<p>This is generated by rebasing modular1.tpl into the base.tpl.
    the Page content using some variable content passed to the template() function in the
    .py file. This is variable --> {{variable}}</p>
